// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv69nidWma3XBK4zMTNAWun4v3u7ER4uo',
    appId: '1:1030940959331:web:b293582b85d68267210e56',
    messagingSenderId: '1030940959331',
    projectId: 'all-product-0001',
    authDomain: 'all-product-0001.firebaseapp.com',
    storageBucket: 'all-product-0001.appspot.com',
    measurementId: 'G-6QTBRGNTKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6g02VW7eLMeneOHOAccefcgyaJLWJEwk',
    appId: '1:1030940959331:android:90e4500210b871d4210e56',
    messagingSenderId: '1030940959331',
    projectId: 'all-product-0001',
    storageBucket: 'all-product-0001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHtorEcLr5QLkEOC1sO3k0luyRIlDbIMU',
    appId: '1:1030940959331:ios:ccca4847eb2026a9210e56',
    messagingSenderId: '1030940959331',
    projectId: 'all-product-0001',
    storageBucket: 'all-product-0001.appspot.com',
    iosBundleId: 'com.example.allProductExam',
  );
}
